name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set lowercase repo name
      id: set_lowercase_repo_name
      run: echo "REPO_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.txt
        push: true
        tags: ghcr.io/${{ env.REPO_NAME_LOWER }}/app-api:latest
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
