name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        file: C:\Users\ramzy\OneDrive\Documents\lab9\Dockerfile.txt
        push: true
        tags: ghcr.io/${{ github.repository | replace('/', '/app-'/ ) | lowercase }}:latest
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
